service:
  name: dad-jokes-service

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  defaultStage: integration
  stages:
    - integration

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  usagePlan:
    quota:
      limit: 1000000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  cfLogs: true
  region: eu-central-1
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

functions:
  twitJoke:
    handler: src/twitJoke.handler
    events:
      - http:
          method: get
          path: v1/twitJoke
          cors: true
